# Generated by Django 2.1.5 on 2019-02-12 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_name', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2019, 2, 12, 7, 53, 12, 573047, tzinfo=utc))),
                ('extensibility', models.CharField(max_length=100)),
                ('stability', models.CharField(max_length=100)),
                ('ductibility', models.CharField(max_length=100)),
                ('toughness', models.CharField(max_length=100)),
                ('strenght', models.CharField(max_length=100)),
                ('pvc_k', models.CharField(max_length=100)),
                ('stabilizer_type', models.CharField(max_length=100)),
                ('stabilizer', models.CharField(max_length=100)),
                ('chalk', models.CharField(max_length=100)),
                ('impact_modifier', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
